# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import slm_pb2 as slm__pb2


class SLMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPhaseMask = channel.unary_unary(
                '/slm.SLM/SetPhaseMask',
                request_serializer=slm__pb2.PhaseMask.SerializeToString,
                response_deserializer=slm__pb2.Response.FromString,
                )
        self.SetLUT = channel.unary_unary(
                '/slm.SLM/SetLUT',
                request_serializer=slm__pb2.LUT.SerializeToString,
                response_deserializer=slm__pb2.Response.FromString,
                )


class SLMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetPhaseMask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLUT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SLMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPhaseMask': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPhaseMask,
                    request_deserializer=slm__pb2.PhaseMask.FromString,
                    response_serializer=slm__pb2.Response.SerializeToString,
            ),
            'SetLUT': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLUT,
                    request_deserializer=slm__pb2.LUT.FromString,
                    response_serializer=slm__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'slm.SLM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SLM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetPhaseMask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/slm.SLM/SetPhaseMask',
            slm__pb2.PhaseMask.SerializeToString,
            slm__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetLUT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/slm.SLM/SetLUT',
            slm__pb2.LUT.SerializeToString,
            slm__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
