# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slm.proto',
  package='slm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tslm.proto\x12\x03slm\"=\n\tPhaseMask\x12\x11\n\tphasemask\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"\x12\n\x03LUT\x12\x0b\n\x03lut\x18\x04 \x01(\x0c\",\n\x08Response\x12\x11\n\tcompleted\x18\x05 \x01(\x08\x12\r\n\x05\x65rror\x18\x06 \x01(\t2[\n\x03SLM\x12/\n\x0cSetPhaseMask\x12\x0e.slm.PhaseMask\x1a\r.slm.Response\"\x00\x12#\n\x06SetLUT\x12\x08.slm.LUT\x1a\r.slm.Response\"\x00\x62\x06proto3'
)




_PHASEMASK = _descriptor.Descriptor(
  name='PhaseMask',
  full_name='slm.PhaseMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='phasemask', full_name='slm.PhaseMask.phasemask', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='slm.PhaseMask.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='slm.PhaseMask.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=79,
)


_LUT = _descriptor.Descriptor(
  name='LUT',
  full_name='slm.LUT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lut', full_name='slm.LUT.lut', index=0,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=99,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='slm.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='completed', full_name='slm.Response.completed', index=0,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='slm.Response.error', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['PhaseMask'] = _PHASEMASK
DESCRIPTOR.message_types_by_name['LUT'] = _LUT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhaseMask = _reflection.GeneratedProtocolMessageType('PhaseMask', (_message.Message,), {
  'DESCRIPTOR' : _PHASEMASK,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.PhaseMask)
  })
_sym_db.RegisterMessage(PhaseMask)

LUT = _reflection.GeneratedProtocolMessageType('LUT', (_message.Message,), {
  'DESCRIPTOR' : _LUT,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.LUT)
  })
_sym_db.RegisterMessage(LUT)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.Response)
  })
_sym_db.RegisterMessage(Response)



_SLM = _descriptor.ServiceDescriptor(
  name='SLM',
  full_name='slm.SLM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=147,
  serialized_end=238,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetPhaseMask',
    full_name='slm.SLM.SetPhaseMask',
    index=0,
    containing_service=None,
    input_type=_PHASEMASK,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetLUT',
    full_name='slm.SLM.SetLUT',
    index=1,
    containing_service=None,
    input_type=_LUT,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLM)

DESCRIPTOR.services_by_name['SLM'] = _SLM

# @@protoc_insertion_point(module_scope)
